// Generated by delombok at Fri Nov 04 22:13:55 CST 2022
package org.mineacademy.fo;

import javax.annotation.Nullable;
import org.bukkit.ChatColor;
import org.bukkit.entity.LivingEntity;
import org.bukkit.entity.Player;
import org.mineacademy.fo.remain.Remain;

/**
 * Utility class for displaying health bar above mobs.
 */
public final class HealthBarUtil {
	/**
	 * The default prefix and suffix
	 */
	private static String prefix = "&8[";
	private static String suffix = "&8]";
	/**
	 * The default health bar colors
	 */
	private static ChatColor remainingColor = ChatColor.DARK_RED;
	private static ChatColor totalColor = ChatColor.GRAY;
	private static ChatColor deadColor = ChatColor.BLACK;

	/**
	 * Formats and displays the health bar as action bar.
	 *
	 * @param displayTo    the player to whom to display
	 * @param displayAbout the entity from which to measure
	 * @param damage       the damage from {@link EntityDamageByEntityEvent} event,
	 *                     or just set 0 to not subtract anything from health.
	 */
	public static void display(final Player displayTo, final LivingEntity displayAbout, final double damage) {
		display(displayTo, displayAbout, null, damage);
	}

	/**
	 * Formats and displays the health bar as action bar.
	 *
	 * @param displayTo
	 * @param displayAbout
	 * @param damagedEntityName
	 * @param damage
	 */
	public static void display(final Player displayTo, final LivingEntity displayAbout, @Nullable final String damagedEntityName, final double damage) {
		final int maxHealth = Remain.getMaxHealth(displayAbout);
		final int health = Remain.getHealth(displayAbout);
		final String name = Common.getOrEmpty(damagedEntityName);
		final String formatted = (name.isEmpty() ? ItemUtil.bountifyCapitalized(displayAbout.getType()) : name) + " - " + getHealthMessage(health, maxHealth, (int) damage);
		Remain.sendActionBar(displayTo, formatted);
	}

	/* Creates a new health component */
	private static String getHealthMessage(final int health, final int maxHealth, final int damage) {
		final int remainingHealth = health - damage;
		return remainingHealth > 0 ? formatHealth(remainingHealth, maxHealth) : formatDeath(maxHealth);
	}

	/* Fills up the graphics of health indicator */
	private static String formatHealth(final int remainingHealth, final int maxHealth) {
		if (maxHealth > 30) return formatMuchHealth(remainingHealth, maxHealth);
		// Fill the remaining health
		String left = "";
		{
			for (int i = 0; i < remainingHealth; i++) left += "|";
		}
		// Fill max health - remaining
		String max = "";
		{
			for (int i = 0; i < maxHealth - left.length(); i++) max += "|";
		}
		return prefix + remainingColor + left + totalColor + max + suffix;
	}

	/* Fills up the graphics if the health is too high */
	private static String formatMuchHealth(final int remaining, final int max) {
		return prefix + remainingColor + remaining + " &8/ " + totalColor + max + suffix;
	}

	/* Fills up the graphic if the health is 0 */
	private static String formatDeath(final int maxHealth) {
		String max = "";
		if (maxHealth > 30) max = "-0-";
		 else for (int i = 0; i < maxHealth; i++) max += "|";
		return prefix + deadColor + max + suffix;
	}

	@java.lang.SuppressWarnings("all")
	private HealthBarUtil() {
	}

	/**
	 * The default prefix and suffix
	 */
	@java.lang.SuppressWarnings("all")
	public static void setPrefix(final String prefix) {
		HealthBarUtil.prefix = prefix;
	}

	@java.lang.SuppressWarnings("all")
	public static void setSuffix(final String suffix) {
		HealthBarUtil.suffix = suffix;
	}

	/**
	 * The default health bar colors
	 */
	@java.lang.SuppressWarnings("all")
	public static void setRemainingColor(final ChatColor remainingColor) {
		HealthBarUtil.remainingColor = remainingColor;
	}

	@java.lang.SuppressWarnings("all")
	public static void setTotalColor(final ChatColor totalColor) {
		HealthBarUtil.totalColor = totalColor;
	}

	@java.lang.SuppressWarnings("all")
	public static void setDeadColor(final ChatColor deadColor) {
		HealthBarUtil.deadColor = deadColor;
	}
}
