// Generated by delombok at Fri Nov 04 22:13:54 CST 2022
package org.mineacademy.fo.remain;

import org.mineacademy.fo.Common;

/**
 * A wrapper for BarStyle from bukkit
 */
public enum CompBarStyle {
	/**
	 * Makes the boss bar solid (no segments)
	 */
	SOLID("SOLID", "SOLID"), /**
	 * Splits the boss bar into 6 segments
	 */
	SEGMENTED_6("SEGMENTED_6", "SEG6"), /**
	 * Splits the boss bar into 10 segments
	 */
	SEGMENTED_10("SEGMENTED_10", "SEG10"), /**
	 * Splits the boss bar into 12 segments
	 */
	SEGMENTED_12("SEGMENTED_12", "SEG12"), /**
	 * Splits the boss bar into 20 segments
	 */
	SEGMENTED_20("SEGMENTED_20", "SEG20");
	private final String key;
	private final String shortKey;

	/**
	 * Attempt to load CompBarStyle from the given key
	 *
	 * @param key
	 * @return
	 */
	public static CompBarStyle fromKey(String key) {
		for (final CompBarStyle mode : values()) if (mode.key.equalsIgnoreCase(key) || mode.shortKey.equalsIgnoreCase(key)) return mode;
		throw new IllegalArgumentException("No such CompBarStyle: " + key + ". Available: " + Common.join(values()));
	}

	@Override
	public String toString() {
		return this.key;
	}

	@java.lang.SuppressWarnings("all")
	private CompBarStyle(final String key, final String shortKey) {
		this.key = key;
		this.shortKey = shortKey;
	}

	@java.lang.SuppressWarnings("all")
	public String getKey() {
		return this.key;
	}

	@java.lang.SuppressWarnings("all")
	public String getShortKey() {
		return this.shortKey;
	}
}
