// Generated by delombok at Fri Nov 04 22:13:55 CST 2022
package org.mineacademy.fo.remain;

import org.mineacademy.fo.Common;

/**
 * A wrapper for BarColor from bukkit
 */
public enum CompBarColor {
	PINK("PINK"), BLUE("BLUE"), RED("RED"), GREEN("GREEN"), YELLOW("YELLOW"), PURPLE("PURPLE"), WHITE("WHITE");
	private final String key;

	/**
	 * Attempt to load CompBarColor from the given key
	 *
	 * @param key
	 * @return
	 */
	public static CompBarColor fromKey(String key) {
		for (final CompBarColor mode : values()) if (mode.key.equalsIgnoreCase(key)) return mode;
		throw new IllegalArgumentException("No such CompBarColor: " + key + ". Available: " + Common.join(values()));
	}

	@Override
	public String toString() {
		return this.key;
	}

	@java.lang.SuppressWarnings("all")
	private CompBarColor(final String key) {
		this.key = key;
	}

	@java.lang.SuppressWarnings("all")
	public String getKey() {
		return this.key;
	}
}
