// Generated by delombok at Fri Nov 04 22:13:55 CST 2022
package org.mineacademy.fo.exception;

/**
 * Represents a silent exception thrown then handling commands,
 * this will only send the command sender a message
 */
public class CommandException extends RuntimeException {
	private static final long serialVersionUID = 1L;
	/**
	 * The messages to send to the command sender
	 */
	private final String[] messages;

	/**
	 * Create a new command exception with messages for the command sender
	 *
	 * @param messages
	 */
	public CommandException(String... messages) {
		super("");
		this.messages = messages;
	}

	/**
	 * The messages to send to the command sender
	 */
	@java.lang.SuppressWarnings("all")
	public String[] getMessages() {
		return this.messages;
	}
}
