// Generated by delombok at Fri Nov 04 22:13:55 CST 2022
package org.mineacademy.fo.exception;

/**
 * Thrown when we load data from data.db but they have a location with a world
 * that no longer exists
 */
public final class InvalidWorldException extends RuntimeException {
	private static final long serialVersionUID = 1L;
	/**
	 * The world that was invali
	 */
	private final String world;

	public InvalidWorldException(String message, String world) {
		super(message);
		this.world = world;
	}

	/**
	 * The world that was invali
	 */
	@java.lang.SuppressWarnings("all")
	public String getWorld() {
		return this.world;
	}
}
