// Generated by delombok at Fri Nov 04 22:13:55 CST 2022
package org.mineacademy.fo.exception;

/**
 * Thrown when we check a regex, see {@link org.mineacademy.fo.Common#regExMatch(java.util.regex.Matcher)}
 * and the evaluation takes over the given limit
 */
public final class RegexTimeoutException extends RuntimeException {
	private static final long serialVersionUID = 1L;
	/**
	 * The message that was being checked
	 */
	private final String checkedMessage;
	/**
	 * The execution limit in miliseconds
	 */
	private final long executionLimit;

	public RegexTimeoutException(CharSequence checkedMessage, long timeoutLimit) {
		this.checkedMessage = checkedMessage.toString();
		this.executionLimit = timeoutLimit;
	}

	/**
	 * The message that was being checked
	 */
	@java.lang.SuppressWarnings("all")
	public String getCheckedMessage() {
		return this.checkedMessage;
	}

	/**
	 * The execution limit in miliseconds
	 */
	@java.lang.SuppressWarnings("all")
	public long getExecutionLimit() {
		return this.executionLimit;
	}
}
