// Generated by delombok at Fri Nov 04 22:13:54 CST 2022
package org.mineacademy.fo.event;

import org.bukkit.entity.Player;
import org.bukkit.event.HandlerList;
import org.bukkit.inventory.Inventory;
import org.mineacademy.fo.menu.Menu;

/**
 * Triggered when a menu is closed from a player at the very end of the pipeline.
 */
public final class MenuCloseEvent extends SimpleEvent {
	private static final HandlerList handlers = new HandlerList();
	/**
	 * The menu. Use {@link #getDrawer()} to edit how menu items will look like.
	 */
	private final Menu menu;
	/**
	 * The inventory as it looked like when closing
	 */
	private final Inventory inventory;
	/**
	 * The player
	 */
	private final Player player;
	/**
	 * Should we prevent to display this menu?
	 */
	private boolean cancelled;

	@Override
	public HandlerList getHandlers() {
		return handlers;
	}

	public static HandlerList getHandlerList() {
		return handlers;
	}

	/**
	 * The menu. Use {@link #getDrawer()} to edit how menu items will look like.
	 */
	@java.lang.SuppressWarnings("all")
	public Menu getMenu() {
		return this.menu;
	}

	/**
	 * The inventory as it looked like when closing
	 */
	@java.lang.SuppressWarnings("all")
	public Inventory getInventory() {
		return this.inventory;
	}

	/**
	 * The player
	 */
	@java.lang.SuppressWarnings("all")
	public Player getPlayer() {
		return this.player;
	}

	/**
	 * Should we prevent to display this menu?
	 */
	@java.lang.SuppressWarnings("all")
	public boolean isCancelled() {
		return this.cancelled;
	}

	@java.lang.SuppressWarnings("all")
	public MenuCloseEvent(final Menu menu, final Inventory inventory, final Player player) {
		this.menu = menu;
		this.inventory = inventory;
		this.player = player;
	}

	/**
	 * Should we prevent to display this menu?
	 */
	@java.lang.SuppressWarnings("all")
	public void setCancelled(final boolean cancelled) {
		this.cancelled = cancelled;
	}
}
