// Generated by delombok at Fri Nov 04 22:13:54 CST 2022
package org.mineacademy.fo.event;

import org.bukkit.entity.Player;
import org.bukkit.event.Cancellable;
import org.bukkit.event.HandlerList;
import org.mineacademy.fo.menu.Menu;
import org.mineacademy.fo.menu.model.InventoryDrawer;

/**
 * Triggered when a menu is opened for a player
 */
public final class MenuOpenEvent extends SimpleEvent implements Cancellable {
	private static final HandlerList handlers = new HandlerList();
	/**
	 * The menu. Use {@link #getDrawer()} to edit how menu items will look like.
	 */
	private final Menu menu;
	/**
	 * The drawer that contains prepared items to render for the player
	 * Use this to edit how the menu will look like
	 */
	private final InventoryDrawer drawer;
	/**
	 * The player
	 */
	private final Player player;
	/**
	 * Should we prevent to display this menu?
	 */
	private boolean cancelled;

	@Override
	public HandlerList getHandlers() {
		return handlers;
	}

	public static HandlerList getHandlerList() {
		return handlers;
	}

	/**
	 * The menu. Use {@link #getDrawer()} to edit how menu items will look like.
	 */
	@java.lang.SuppressWarnings("all")
	public Menu getMenu() {
		return this.menu;
	}

	/**
	 * The drawer that contains prepared items to render for the player
	 * Use this to edit how the menu will look like
	 */
	@java.lang.SuppressWarnings("all")
	public InventoryDrawer getDrawer() {
		return this.drawer;
	}

	/**
	 * The player
	 */
	@java.lang.SuppressWarnings("all")
	public Player getPlayer() {
		return this.player;
	}

	/**
	 * Should we prevent to display this menu?
	 */
	@java.lang.SuppressWarnings("all")
	public boolean isCancelled() {
		return this.cancelled;
	}

	@java.lang.SuppressWarnings("all")
	public MenuOpenEvent(final Menu menu, final InventoryDrawer drawer, final Player player) {
		this.menu = menu;
		this.drawer = drawer;
		this.player = player;
	}

	/**
	 * Should we prevent to display this menu?
	 */
	@java.lang.SuppressWarnings("all")
	public void setCancelled(final boolean cancelled) {
		this.cancelled = cancelled;
	}
}
