// Generated by delombok at Fri Nov 04 22:13:54 CST 2022
package org.mineacademy.fo.event;

import org.bukkit.entity.Projectile;
import org.bukkit.event.Cancellable;
import org.bukkit.event.HandlerList;
import org.mineacademy.fo.menu.tool.Rocket;

/**
 * The event that is triggered when a {@link Rocket} explodes.
 */
public final class RocketExplosionEvent extends SimpleEvent implements Cancellable {
	private static final HandlerList handlers = new HandlerList();
	/**
	 * The rocket
	 */
	private final Rocket rocket;
	/**
	 * The projectile
	 */
	private final Projectile projectile;
	/**
	 * The power of this explosion
	 */
	private float power;
	/**
	 * Should this explosion break blocks?
	 */
	private boolean breakBlocks;
	/**
	 * Is the event cancelled?
	 */
	private boolean cancelled;

	public RocketExplosionEvent(Rocket rocket, Projectile projectile, float power, boolean breakBlocks) {
		this.rocket = rocket;
		this.projectile = projectile;
		this.power = power;
		this.breakBlocks = breakBlocks;
	}

	@Override
	public HandlerList getHandlers() {
		return handlers;
	}

	public static HandlerList getHandlerList() {
		return handlers;
	}

	/**
	 * The rocket
	 */
	@java.lang.SuppressWarnings("all")
	public Rocket getRocket() {
		return this.rocket;
	}

	/**
	 * The projectile
	 */
	@java.lang.SuppressWarnings("all")
	public Projectile getProjectile() {
		return this.projectile;
	}

	/**
	 * The power of this explosion
	 */
	@java.lang.SuppressWarnings("all")
	public float getPower() {
		return this.power;
	}

	/**
	 * Should this explosion break blocks?
	 */
	@java.lang.SuppressWarnings("all")
	public boolean isBreakBlocks() {
		return this.breakBlocks;
	}

	/**
	 * Is the event cancelled?
	 */
	@java.lang.SuppressWarnings("all")
	public boolean isCancelled() {
		return this.cancelled;
	}

	/**
	 * The power of this explosion
	 */
	@java.lang.SuppressWarnings("all")
	public void setPower(final float power) {
		this.power = power;
	}

	/**
	 * Should this explosion break blocks?
	 */
	@java.lang.SuppressWarnings("all")
	public void setBreakBlocks(final boolean breakBlocks) {
		this.breakBlocks = breakBlocks;
	}

	/**
	 * Is the event cancelled?
	 */
	@java.lang.SuppressWarnings("all")
	public void setCancelled(final boolean cancelled) {
		this.cancelled = cancelled;
	}
}
