// Generated by delombok at Fri Nov 04 22:13:54 CST 2022
package org.mineacademy.fo.event;

/**
 * An extension of {@link SimpleEvent} which also makes your custom events
 * cancellable.
 */
public abstract class SimpleCancellableEvent extends SimpleEvent {
	/**
	 * Is the event cancelled?
	 */
	private boolean cancelled;

	/**
	 * Create a new event indicating whether it is run from
	 * the primary Minecraft server thread or not
	 *
	 * @param async
	 */
	protected SimpleCancellableEvent(boolean async) {
		super(async);
	}

	/**
	 * Is the event cancelled?
	 */
	@java.lang.SuppressWarnings("all")
	public boolean isCancelled() {
		return this.cancelled;
	}

	/**
	 * Is the event cancelled?
	 */
	@java.lang.SuppressWarnings("all")
	public void setCancelled(final boolean cancelled) {
		this.cancelled = cancelled;
	}

	@java.lang.SuppressWarnings("all")
	protected SimpleCancellableEvent() {
	}
}
