// Generated by delombok at Fri Nov 04 22:13:55 CST 2022
package org.mineacademy.fo.conversation;

import org.bukkit.conversations.ConversationContext;
import org.bukkit.conversations.ConversationPrefix;
import org.mineacademy.fo.Common;

/**
 * A simple conversation prefix with a static string
 */
public final class SimplePrefix implements ConversationPrefix {
	/**
	 * The conversation prefix
	 */
	private final String prefix;

	@Override
	public String getPrefix(ConversationContext context) {
		return Common.colorize(this.prefix);
	}

	@java.lang.SuppressWarnings("all")
	public SimplePrefix(final String prefix) {
		this.prefix = prefix;
	}

	/**
	 * The conversation prefix
	 */
	@java.lang.SuppressWarnings("all")
	public String getPrefix() {
		return this.prefix;
	}
}
