// Generated by delombok at Fri Nov 04 22:13:55 CST 2022
package org.mineacademy.fo.model;

import org.bukkit.enchantments.Enchantment;

/**
 * A simple wrapper for enchants
 */
public final class SimpleEnchant {
	/**
	 * The enchantment
	 */
	private final Enchantment enchant;
	/**
	 * The level
	 */
	private final int level;

	/**
	 * Creates a new enchantment of level 1
	 *
	 * @param enchant the enchantment
	 */
	public SimpleEnchant(Enchantment enchant) {
		this(enchant, 1);
	}

	/**
	 * The enchantment
	 */
	@java.lang.SuppressWarnings("all")
	public Enchantment getEnchant() {
		return this.enchant;
	}

	/**
	 * The level
	 */
	@java.lang.SuppressWarnings("all")
	public int getLevel() {
		return this.level;
	}

	@java.lang.SuppressWarnings("all")
	public SimpleEnchant(final Enchantment enchant, final int level) {
		this.enchant = enchant;
		this.level = level;
	}
}
