// Generated by delombok at Fri Nov 04 22:13:55 CST 2022
package org.mineacademy.fo.model;

/**
 * A simple placeholder for storing three values
 *
 * @param <A>
 * @param <B>
 * @param <C>
 */
public final class Triple<A, B, C> {
	/**
	 * The first value we hold
	 */
	private final A first;
	/**
	 * The second value we hold
	 */
	private final B second;
	/**
	 * The third value we hold
	 */
	private final C third;

	@java.lang.SuppressWarnings("all")
	public Triple(final A first, final B second, final C third) {
		this.first = first;
		this.second = second;
		this.third = third;
	}

	/**
	 * The first value we hold
	 */
	@java.lang.SuppressWarnings("all")
	public A getFirst() {
		return this.first;
	}

	/**
	 * The second value we hold
	 */
	@java.lang.SuppressWarnings("all")
	public B getSecond() {
		return this.second;
	}

	/**
	 * The third value we hold
	 */
	@java.lang.SuppressWarnings("all")
	public C getThird() {
		return this.third;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof Triple)) return false;
		final Triple<?, ?, ?> other = (Triple<?, ?, ?>) o;
		final java.lang.Object this$first = this.getFirst();
		final java.lang.Object other$first = other.getFirst();
		if (this$first == null ? other$first != null : !this$first.equals(other$first)) return false;
		final java.lang.Object this$second = this.getSecond();
		final java.lang.Object other$second = other.getSecond();
		if (this$second == null ? other$second != null : !this$second.equals(other$second)) return false;
		final java.lang.Object this$third = this.getThird();
		final java.lang.Object other$third = other.getThird();
		if (this$third == null ? other$third != null : !this$third.equals(other$third)) return false;
		return true;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $first = this.getFirst();
		result = result * PRIME + ($first == null ? 43 : $first.hashCode());
		final java.lang.Object $second = this.getSecond();
		result = result * PRIME + ($second == null ? 43 : $second.hashCode());
		final java.lang.Object $third = this.getThird();
		result = result * PRIME + ($third == null ? 43 : $third.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Triple(first=" + this.getFirst() + ", second=" + this.getSecond() + ", third=" + this.getThird() + ")";
	}
}
