// Generated by delombok at Fri Nov 04 22:13:55 CST 2022
package org.mineacademy.fo.remain.internal;

import org.bukkit.Location;
import org.mineacademy.fo.remain.CompBarColor;
import org.mineacademy.fo.remain.CompBarStyle;
import org.mineacademy.fo.remain.Remain;

/**
 * Represents the fake dragon entity
 * <p>
 * Typically you dont have to use this at all.
 */
abstract class NMSDragon {
	private float maxHealth = 200;
	private int x;
	private int y;
	private int z;
	private int pitch = 0;
	private int yaw = 0;
	private byte xvel = 0;
	private byte yvel = 0;
	private byte zvel = 0;
	private float health = 0;
	private boolean visible = false;
	private String name;
	private Object world;
	protected CompBarColor barColor;
	protected CompBarStyle barStyle;

	NMSDragon(String name, Location loc, int percent) {
		this.name = name;
		this.x = loc.getBlockX();
		this.y = loc.getBlockY();
		this.z = loc.getBlockZ();
		this.health = percent / 100.0F * this.maxHealth;
		this.world = Remain.getHandleWorld(loc.getWorld());
	}

	NMSDragon(String name, Location loc) {
		this.name = name;
		this.x = loc.getBlockX();
		this.y = loc.getBlockY();
		this.z = loc.getBlockZ();
		this.world = Remain.getHandleWorld(loc.getWorld());
	}

	void setHealth(int percent) {
		this.health = percent / 100.0F * this.maxHealth;
	}

	void setHealthF(float health) {
		this.health = health;
	}

	abstract Object getSpawnPacket();

	abstract Object getDestroyPacket();

	abstract Object getMetaPacket(Object watcher);

	abstract Object getTeleportPacket(Location loc);

	abstract Object getWatcher();

	abstract Object getNMSEntity();

	@java.lang.SuppressWarnings("all")
	public float getMaxHealth() {
		return this.maxHealth;
	}

	@java.lang.SuppressWarnings("all")
	public int getX() {
		return this.x;
	}

	@java.lang.SuppressWarnings("all")
	public int getY() {
		return this.y;
	}

	@java.lang.SuppressWarnings("all")
	public int getZ() {
		return this.z;
	}

	@java.lang.SuppressWarnings("all")
	public int getPitch() {
		return this.pitch;
	}

	@java.lang.SuppressWarnings("all")
	public int getYaw() {
		return this.yaw;
	}

	@java.lang.SuppressWarnings("all")
	public byte getXvel() {
		return this.xvel;
	}

	@java.lang.SuppressWarnings("all")
	public byte getYvel() {
		return this.yvel;
	}

	@java.lang.SuppressWarnings("all")
	public byte getZvel() {
		return this.zvel;
	}

	@java.lang.SuppressWarnings("all")
	public float getHealth() {
		return this.health;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isVisible() {
		return this.visible;
	}

	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}

	@java.lang.SuppressWarnings("all")
	public Object getWorld() {
		return this.world;
	}

	@java.lang.SuppressWarnings("all")
	public CompBarColor getBarColor() {
		return this.barColor;
	}

	@java.lang.SuppressWarnings("all")
	public CompBarStyle getBarStyle() {
		return this.barStyle;
	}

	@java.lang.SuppressWarnings("all")
	public void setMaxHealth(final float maxHealth) {
		this.maxHealth = maxHealth;
	}

	@java.lang.SuppressWarnings("all")
	public void setX(final int x) {
		this.x = x;
	}

	@java.lang.SuppressWarnings("all")
	public void setY(final int y) {
		this.y = y;
	}

	@java.lang.SuppressWarnings("all")
	public void setZ(final int z) {
		this.z = z;
	}

	@java.lang.SuppressWarnings("all")
	public void setPitch(final int pitch) {
		this.pitch = pitch;
	}

	@java.lang.SuppressWarnings("all")
	public void setYaw(final int yaw) {
		this.yaw = yaw;
	}

	@java.lang.SuppressWarnings("all")
	public void setXvel(final byte xvel) {
		this.xvel = xvel;
	}

	@java.lang.SuppressWarnings("all")
	public void setYvel(final byte yvel) {
		this.yvel = yvel;
	}

	@java.lang.SuppressWarnings("all")
	public void setZvel(final byte zvel) {
		this.zvel = zvel;
	}

	@java.lang.SuppressWarnings("all")
	public void setVisible(final boolean visible) {
		this.visible = visible;
	}

	@java.lang.SuppressWarnings("all")
	public void setName(final String name) {
		this.name = name;
	}

	@java.lang.SuppressWarnings("all")
	public void setWorld(final Object world) {
		this.world = world;
	}

	@java.lang.SuppressWarnings("all")
	public void setBarColor(final CompBarColor barColor) {
		this.barColor = barColor;
	}

	@java.lang.SuppressWarnings("all")
	public void setBarStyle(final CompBarStyle barStyle) {
		this.barStyle = barStyle;
	}
}
